BEGIN;

INSERT INTO stations (station_naptan, common_name_short) VALUES
('940GZZLUAMS', 'Amersham'),
('940GZZLUCAL', 'Chalfont & Latimer'),
('940GZZLUCSM', 'Chesham'),
('940GZZLUBKH', 'Buckhurst Hill'),
('940GZZLUCWL', 'Chigwell'),
('940GZZLUDBN', 'Debden'),
('940GZZLUEPG', 'Epping'),
('940GZZLUGGH', 'Grange Hill'),
('940GZZLULGN', 'Loughton'),
('940GZZLUTHB', 'Theydon Bois'),
('940GZZLUCXY', 'Croxley'),
('940GZZLUCYD', 'Chorleywood'),
('940GZZLUMPK', 'Moor Park'),
('940GZZLURKW', 'Rickmansworth'),
('940GZZLUWAF', 'Watford'),
('940GZZLUACT', 'Acton Town'),
('940GZZLUACY', 'Archway'),
('940GZZLUADE', 'Aldgate East'),
('940GZZLUAGL', 'Angel'),
('940GZZLUALD', 'Aldgate'),
('940GZZLUALP', 'Alperton'),
('940GZZLUASG', 'Arnos Grove'),
('940GZZLUASL', 'Arsenal'),
('940GZZLUBBB', 'Bromley-By-Bow'),
('940GZZLUBBN', 'Barbican'),
('940GZZLUBDS', 'Bounds Green'),
('940GZZLUBEC', 'Becontree'),
('940GZZLUBKE', 'Barkingside'),
('940GZZLUBKF', 'Blackfriars'),
('940GZZLUBLG', 'Bethnal Green'),
('940GZZLUBLM', 'Balham'),
('940GZZLUBMY', 'Bermondsey'),
('940GZZLUBND', 'Bond Street'),
('940GZZLUBNK', 'Bank'),
('940GZZLUBOR', 'Borough'),
('940GZZLUBOS', 'Boston Manor'),
('940GZZLUBSC', 'Barons Court'),
('940GZZLUBST', 'Baker Street'),
('940GZZLUBTK', 'Burnt Oak'),
('940GZZLUBTX', 'Brent Cross'),
('940GZZLUBWR', 'Bow Road'),
('940GZZLUBWT', 'Bayswater'),
('940GZZLUBXN', 'Brixton'),
('940GZZLUBZP', 'Belsize Park'),
('940GZZLUCAR', 'Caledonian Road'),
('940GZZLUCFM', 'Chalk Farm'),
('940GZZLUCGN', 'Covent Garden'),
('940GZZLUCHL', 'Chancery Lane'),
('940GZZLUCHX', 'Charing Cross'),
('940GZZLUCKS', 'Cockfosters'),
('940GZZLUCND', 'Colindale'),
('940GZZLUCPC', 'Clapham Common'),
('940GZZLUCPK', 'Canons Park'),
('940GZZLUCPN', 'Clapham North'),
('940GZZLUCPS', 'Clapham South'),
('940GZZLUCSD', 'Colliers Wood'),
('940GZZLUCST', 'Cannon Street'),
('940GZZLUCTN', 'Camden Town'),
('940GZZLUCWP', 'Chiswick Park'),
('940GZZLUCYF', 'Canary Wharf Station'),
('940GZZLUDGE', 'Dagenham East'),
('940GZZLUDGY', 'Dagenham Heathway'),
('940GZZLUDOH', 'Dollis Hill'),
('940GZZLUEAC', 'Elephant & Castle'),
('940GZZLUEAE', 'Eastcote'),
('940GZZLUEAN', 'East Acton'),
('940GZZLUECM', 'Ealing Common'),
('940GZZLUECT', 'Earl''s Court'),
('940GZZLUEFY', 'East Finchley'),
('940GZZLUEHM', 'East Ham'),
('940GZZLUEMB', 'Embankment'),
('940GZZLUEPK', 'Elm Park'),
('940GZZLUEPY', 'East Putney'),
('940GZZLUERB', 'Edgware Road (Bakerloo Line)'),
('940GZZLUERC', 'Edgware Road (Circle Line)'),
('940GZZLUESQ', 'Euston Square'),
('940GZZLUFBY', 'Fulham Broadway'),
('940GZZLUFCN', 'Farringdon'),
('940GZZLUFLP', 'Fairlop'),
('940GZZLUFPK', 'Finsbury Park'),
('940GZZLUFYC', 'Finchley Central'),
('940GZZLUFYR', 'Finchley Road'),
('940GZZLUGDG', 'Goodge Street'),
('940GZZLUGGN', 'Golders Green'),
('940GZZLUGHK', 'Goldhawk Road'),
('940GZZLUGPK', 'Green Park'),
('940GZZLUGPS', 'Great Portland Street'),
('940GZZLUGTH', 'Gants Hill'),
('940GZZLUGTR', 'Gloucester Road'),
('940GZZLUHBN', 'Holborn'),
('940GZZLUHBT', 'High Barnet'),
('940GZZLUHCH', 'Hornchurch'),
('940GZZLUHCL', 'Hendon Central'),
('940GZZLUHGD', 'Hillingdon'),
('940GZZLUHGR', 'Hanger Lane'),
('940GZZLUHGT', 'Highgate'),
('940GZZLUHNX', 'Hatton Cross'),
('940GZZLUHPC', 'Hyde Park Corner'),
('940GZZLUHPK', 'Holland Park'),
('940GZZLUHRC', 'Heathrow Terminals 2 & 3'),
('940GZZLUHSD', 'Hammersmith (Dist&Picc Line)'),
('940GZZLUHSK', 'High Street Kensington'),
('940GZZLUHTD', 'Hampstead'),
('940GZZLUHWC', 'Hounslow Central'),
('940GZZLUHWE', 'Hounslow East'),
('940GZZLUHWT', 'Hounslow West'),
('940GZZLUHWY', 'Holloway Road'),
('940GZZLUICK', 'Ickenham'),
('940GZZLUKBN', 'Kilburn'),
('940GZZLUKBY', 'Kingsbury'),
('940GZZLUKNB', 'Knightsbridge'),
('940GZZLUKNG', 'Kennington'),
('940GZZLUKPK', 'Kilburn Park'),
('940GZZLUKSX', 'King''s Cross St.Pancras'),
('940GZZLULAD', 'Ladbroke Grove'),
('940GZZLULBN', 'Lambeth North'),
('940GZZLULGT', 'Lancaster Gate'),
('940GZZLULNB', 'London Bridge'),
('940GZZLULRD', 'Latimer Road'),
('940GZZLULSQ', 'Leicester Square'),
('940GZZLULVT', 'Liverpool Street'),
('940GZZLULYN', 'Leyton'),
('940GZZLULYS', 'Leytonstone'),
('940GZZLUMBA', 'Marble Arch'),
('940GZZLUMDN', 'Morden'),
('940GZZLUMED', 'Mile End'),
('940GZZLUMHL', 'Mill Hill East'),
('940GZZLUMMT', 'Monument'),
('940GZZLUMRH', 'Manor House'),
('940GZZLUMSH', 'Mansion House'),
('940GZZLUMTC', 'Mornington Crescent'),
('940GZZLUMVL', 'Maida Vale'),
('940GZZLUNAN', 'North Acton'),
('940GZZLUNBP', 'Newbury Park'),
('940GZZLUNDN', 'Neasden'),
('940GZZLUNEN', 'North Ealing'),
('940GZZLUNFD', 'Northfields'),
('940GZZLUNGW', 'North Greenwich'),
('940GZZLUNHA', 'North Harrow'),
('940GZZLUNHG', 'Notting Hill Gate'),
('940GZZLUNHT', 'Northolt'),
('940GZZLUNKP', 'Northwick Park'),
('940GZZLUNOW', 'Northwood'),
('940GZZLUNWH', 'Northwood Hills'),
('940GZZLUOAK', 'Oakwood'),
('940GZZLUOSY', 'Osterley'),
('940GZZLUOVL', 'Oval'),
('940GZZLUOXC', 'Oxford Circus'),
('940GZZLUPAC', 'Paddington'),
('940GZZLUPAH', 'Paddington (H&C Line)'),
('940GZZLUPCC', 'Piccadilly Circus'),
('940GZZLUPCO', 'Pimlico'),
('940GZZLUPKR', 'Park Royal'),
('940GZZLUPLW', 'Plaistow'),
('940GZZLUPNR', 'Pinner'),
('940GZZLUPRD', 'Preston Road'),
('940GZZLUPSG', 'Parsons Green'),
('940GZZLUPVL', 'Perivale'),
('940GZZLUPYB', 'Putney Bridge'),
('940GZZLUQBY', 'Queensbury'),
('940GZZLUQWY', 'Queensway'),
('940GZZLURBG', 'Redbridge'),
('940GZZLURGP', 'Regent''s Park'),
('940GZZLURSG', 'Ruislip Gardens'),
('940GZZLURSM', 'Ruislip Manor'),
('940GZZLURSP', 'Ruislip'),
('940GZZLURSQ', 'Russell Square'),
('940GZZLURVP', 'Ravenscourt Park'),
('940GZZLURVY', 'Roding Valley'),
('940GZZLURYL', 'Rayners Lane'),
('940GZZLURYO', 'Royal Oak'),
('940GZZLUSBC', 'Shepherd''s Bush (Central Line)'),
('940GZZLUSBM', 'Shepherd''s Bush Market'),
('940GZZLUSEA', 'South Ealing'),
('940GZZLUSFB', 'Stamford Brook'),
('940GZZLUSFS', 'Southfields'),
('940GZZLUSGN', 'Stepney Green'),
('940GZZLUSGT', 'Southgate'),
('940GZZLUSHH', 'South Harrow'),
('940GZZLUSJP', 'St. James''s Park'),
('940GZZLUSJW', 'St John''s Wood'),
('940GZZLUSKS', 'South Kensington'),
('940GZZLUSKW', 'Stockwell'),
('940GZZLUSNB', 'Snaresbrook'),
('940GZZLUSPU', 'St. Paul''s'),
('940GZZLUSSQ', 'Sloane Square'),
('940GZZLUSTM', 'Stanmore'),
('940GZZLUSUH', 'Sudbury Hill'),
('940GZZLUSUT', 'Sudbury Town'),
('940GZZLUSVS', 'Seven Sisters'),
('940GZZLUSWC', 'Swiss Cottage'),
('940GZZLUSWF', 'South Woodford'),
('940GZZLUSWK', 'Southwark'),
('940GZZLUSWN', 'South Wimbledon'),
('940GZZLUTAW', 'Totteridge & Whetstone'),
('940GZZLUTBC', 'Tooting Bec'),
('940GZZLUTBY', 'Tooting Broadway'),
('940GZZLUTCR', 'Tottenham Court Road'),
('940GZZLUTFP', 'Tufnell Park'),
('940GZZLUTMP', 'Temple'),
('940GZZLUTNG', 'Turnham Green'),
('940GZZLUTPN', 'Turnpike Lane'),
('940GZZLUTWH', 'Tower Hill'),
('940GZZLUUPB', 'Upminster Bridge'),
('940GZZLUUPK', 'Upton Park'),
('940GZZLUUPY', 'Upney'),
('940GZZLUUXB', 'Uxbridge'),
('940GZZLUVIC', 'Victoria'),
('940GZZLUVXL', 'Vauxhall'),
('940GZZLUWCY', 'White City'),
('940GZZLUWFN', 'West Finchley'),
('940GZZLUWHP', 'West Hampstead Station'),
('940GZZLUWHW', 'West Harrow'),
('940GZZLUWIG', 'Willesden Green'),
('940GZZLUWIP', 'Wimbledon Park'),
('940GZZLUWKA', 'Warwick Avenue'),
('940GZZLUWKN', 'West Kensington'),
('940GZZLUWLA', 'Wood Lane'),
('940GZZLUWLO', 'Waterloo'),
('940GZZLUWOF', 'Woodford'),
('940GZZLUWOG', 'Wood Green'),
('940GZZLUWOP', 'Woodside Park'),
('940GZZLUWRR', 'Warren Street'),
('940GZZLUWSD', 'Wanstead'),
('940GZZLUWSM', 'Westminster'),
('940GZZLUWSP', 'Westbourne Park'),
('940GZZLUWTA', 'West Acton'),
('940GZZLUWYP', 'Wembley Park'),
('940GZZBPSUST', 'Battersea Power Station'),
('940GZZLUBKG', 'Barking'),
('940GZZLUBLR', 'Blackhorse Road'),
('940GZZLUCGT', 'Canning Town'),
('940GZZLUCWR', 'Canada Water'),
('940GZZLUEBY', 'Ealing Broadway'),
('940GZZLUEGW', 'Edgware'),
('940GZZLUEUS', 'Euston'),
('940GZZLUGBY', 'Gunnersbury'),
('940GZZLUGFD', 'Greenford'),
('940GZZLUHAI', 'Highbury & Islington'),
('940GZZLUHAW', 'Harrow & Wealdstone'),
('940GZZLUHLT', 'Hainault'),
('940GZZLUHOH', 'Harrow-on-the-Hill'),
('940GZZLUHR4', 'Heathrow Terminal 4'),
('940GZZLUHR5', 'Heathrow Terminal 5'),
('940GZZLUHSC', 'Hammersmith (H&C Line)'),
('940GZZLUHSN', 'Harlesden'),
('940GZZLUKEN', 'Kenton'),
('940GZZLUKOY', 'Kensington (Olympia)'),
('940GZZLUKSH', 'Kentish Town'),
('940GZZLUKSL', 'Kensal Green'),
('940GZZLUKWG', 'Kew Gardens'),
('940GZZLUMGT', 'Moorgate'),
('940GZZLUMYB', 'Marylebone'),
('940GZZLUNWY', 'North Wembley'),
('940GZZLUODS', 'Old Street'),
('940GZZLUQPS', 'Queen''s Park'),
('940GZZLURMD', 'Richmond'),
('940GZZLUSGP', 'Stonebridge Park'),
('940GZZLUSKT', 'South Kenton'),
('940GZZLUSRP', 'South Ruislip'),
('940GZZLUSTD', 'Stratford'),
('940GZZLUTMH', 'Tottenham Hale'),
('940GZZLUUPM', 'Upminster'),
('940GZZLUWBN', 'West Brompton'),
('940GZZLUWHM', 'West Ham'),
('940GZZLUWIM', 'Wimbledon'),
('940GZZLUWJN', 'Willesden Junction'),
('940GZZLUWPL', 'Whitechapel'),
('940GZZLUWRP', 'West Ruislip'),
('940GZZLUWWL', 'Walthamstow Central'),
('940GZZLUWYC', 'Wembley Central'),
('940GZZNEUGST', 'Nine Elms');

COMMIT;